FROM docker://nvcr.io/nvidia/tensorflow:19.12-tf1-py3

RUN pip install pillow \
		numpy \
		matplotlib \
		opencv-python \
		awscli \
		scikit-image \
		pyqrcodeng \
 		pandas \
		google_images_download \
		urllib \
		argparse \
		configparser \
